remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
minimal_mistakes_skin: "default" # or air, aqua, contrast, dark, etc.

title: David Su 
#logo:
#description this is under the logo/profile pic
email: yutongdavidsu@gmail.com
phone: (+61) 0423 160 620
linkedin: https://www.linkedin.com/in/david-su-5b041037b/
#show_downloads: true
theme: jekyll-theme-minimal #use this for now, view more at pages.github.com/themes/
